# (auto-generated by run_all_tests.ps1) quick runner to create trade_log.csv for qty checks
import os, sys, glob, csv, argparse
from datetime import datetime

repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# Ensure repo root is in path FIRST, before any engine imports
sys.path.insert(0, repo_root)

# Import engine.config FIRST to establish the namespace package correctly
import engine.config.config
from engine.config.config import Config

import pandas as pd
# Import ResearchEngine directly to avoid namespace package conflicts
import importlib.util
spec = importlib.util.spec_from_file_location("research_engine", os.path.join(repo_root, "research", "backtest", "engine", "research_engine.py"))
research_engine_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(research_engine_module)
ResearchEngine = research_engine_module.ResearchEngine


def find_csv_candidate():
    candidates = [
        os.path.join(repo_root, "data", "historical", "nifty_1m_full.csv"),
        os.path.join(repo_root, "data", "nifty_1m_full.csv"),
        os.path.join(repo_root, "research", "backtest", "data", "market.csv"),
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    p = os.path.join(repo_root, "research", "backtest", "data", "*.csv")
    found = glob.glob(p)
    if found:
        return found[0]
    found = glob.glob(os.path.join(repo_root, "data", "*.csv"))
    if found:
        return found[0]
    return None


def load_csv(p):
    df = pd.read_csv(p)
    dt_cols = [c for c in df.columns if "date" in c.lower() or "time" in c.lower() or "ts" in c.lower()]
    if not dt_cols:
        raise RuntimeError("No datetime-like column in CSV: " + p)
    col = dt_cols[0]
    df[col] = pd.to_datetime(df[col], errors="coerce")
    df = df.dropna(subset=[col]).sort_values(col).reset_index(drop=True)
    return df, col


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", default="2025-07-01", help="Start date YYYY-MM-DD")
    parser.add_argument("--end", default="2025-07-07", help="End date YYYY-MM-DD")
    parser.add_argument("--max-rows", type=int, default=5000, help="Max rows to process (for speed)")
    parser.add_argument("--dry-run", action="store_true", help="Dry run flag (ignored)")
    return parser.parse_args()


def main():
    args = parse_args()

    outdir = os.path.join(repo_root, "research", "backtest", "results")
    os.makedirs(outdir, exist_ok=True)

    csv_path = find_csv_candidate()
    if not csv_path:
        print("ERROR: No CSV candidate found for quick backtest. Place a historical OHLC CSV under data/ or research/backtest/data/")
        sys.exit(2)
    print("Using CSV:", csv_path)

    df, dtcol = load_csv(csv_path)

    # Filter by date range
    start_dt = pd.Timestamp(args.start)
    end_dt = pd.Timestamp(args.end) + pd.Timedelta(days=1)  # inclusive end
    df = df[(df[dtcol] >= start_dt) & (df[dtcol] < end_dt)].reset_index(drop=True)
    print(f"Filtered to {len(df)} rows between {args.start} and {args.end}")

    # Limit rows for speed
    if len(df) > args.max_rows:
        df = df.iloc[:args.max_rows].reset_index(drop=True)
        print(f"Limited to first {args.max_rows} rows for speed")

    engine = ResearchEngine()
    trades = []
    window_size = 60

    for i in range(window_size, len(df) - 1):
        window = df.iloc[i - window_size + 1:i + 1].copy()
        ts = window[dtcol].iloc[-1]
        try:
            signal = engine.check_entry(window, ts)
        except Exception:
            continue
        if signal:
            entry_price = float(window["close"].iloc[-1]) if "close" in window.columns else None
            exit_price = float(df.iloc[i + 1]["close"]) if "close" in df.columns else entry_price
            qty = engine.qty
            lots = engine.lots_per_trade
            gross = None
            if entry_price is not None and exit_price is not None:
                gross = (exit_price - entry_price) * qty
            cost = 0
            try:
                from engine.execution.cost_model import round_trip_cost
                cost = float(round_trip_cost(qty))
            except Exception:
                cost = 0
            net = None if gross is None else gross - cost
            trades.append({
                "case_id": f"auto-{i}",
                "entry_ts": ts.isoformat(),
                "exit_ts": df.iloc[i + 1][dtcol].isoformat(),
                "symbol": "BANKNIFTY",
                "side": signal.get("side") if isinstance(signal, dict) else "NA",
                "qty": int(qty),
                "lots": int(lots),
                "entry_price": entry_price,
                "exit_price": exit_price,
                "exit_reason": "NEXT_CANDLE",
                "gross_pnl": gross,
                "cost": cost,
                "net_pnl": net
            })

    outpath = os.path.join(outdir, "trade_log.csv")
    with open(outpath, "w", newline='', encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["case_id", "entry_ts", "exit_ts", "symbol", "side", "qty", "lots", "entry_price", "exit_price", "exit_reason", "gross_pnl", "cost", "net_pnl"])
        w.writeheader()
        for t in trades:
            w.writerow(t)
    print("Wrote trade log:", outpath, "rows:", len(trades))


if __name__ == "__main__":
    main()